declare module 'react-phone-input-2' {
  import { ComponentType, InputHTMLAttributes } from 'react';

  interface PhoneInputProps extends InputHTMLAttributes<HTMLInputElement> {
    country?: string;
    value?: string;
    onChange?: (value: string) => void;
    onBlur?: (value: string) => void;
    containerClass?: string;
    inputClass?: string;
    buttonClass?: string;
    dropdownClass?: string;
    searchClass?: string;
    searchPlaceholder?: string;
    searchNotFound?: string;
    preferredCountries?: string[];
    enableSearch?: boolean;
    disableSearchIcon?: boolean;
    searchNotFoundPlaceholder?: string;
    searchPlaceholder?: string;
    specialLabel?: string;
    selectProps?: object;
    inputProps?: object;
    buttonProps?: object;
    dropdownProps?: object;
    searchProps?: object;
    containerStyle?: object;
    inputStyle?: object;
    buttonStyle?: object;
    dropdownStyle?: object;
    searchStyle?: object;
    flagStyle?: object;
    countryCodeEditable?: boolean;
    enableAreaCodes?: boolean;
    enableAreaCodeStretch?: boolean;
    disableAreaCodes?: boolean;
    disableCountryCode?: boolean;
    disableDropdown?: boolean;
    dropdownVariant?: string;
    dropdownAlign?: string;
    dropdownPosition?: string;
    dropdownStyle?: object;
    dropdownClass?: string;
    dropdownProps?: object;
    searchStyle?: object;
    searchClass?: string;
    searchProps?: object;
    searchPlaceholder?: string;
    searchNotFound?: string;
    searchNotFoundPlaceholder?: string;
    enableSearch?: boolean;
    disableSearchIcon?: boolean;
    preferredCountries?: string[];
    countryCodeEditable?: boolean;
    enableAreaCodes?: boolean;
    enableAreaCodeStretch?: boolean;
    disableAreaCodes?: boolean;
    disableCountryCode?: boolean;
    disableDropdown?: boolean;
    dropdownVariant?: string;
    dropdownAlign?: string;
    dropdownPosition?: string;
    dropdownStyle?: object;
    dropdownClass?: string;
    dropdownProps?: object;
    searchStyle?: object;
    searchClass?: string;
    searchProps?: object;
    searchPlaceholder?: string;
    searchNotFound?: string;
    searchNotFoundPlaceholder?: string;
    enableSearch?: boolean;
    disableSearchIcon?: boolean;
    preferredCountries?: string[];
  }

  const PhoneInput: ComponentType<PhoneInputProps>;
  export default PhoneInput;
} 